/********************************************************************************************************
 *@Author: Rafael Ricardo Cardona Bravo
 *@Function: Codigo generado desde wsdl como tambien la clase AsyncNewpackage. 
             Esta clase consume un servicio que esta en el servidor local wampserver como ejercicio
 ********************************************************************************************************/

public class newpackage {
    public class MostrarNombreResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class buscarUsuarioCedulaResponse {
        public Boolean return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class MostrarApellidoResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class MostrarNombre {
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class eliminarUsuarioResponse {
        public Boolean return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class actualizarUsuarioResponse {
        public Boolean return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class MostrarDireccionResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class buscarUsuarioCedula {
        public String arg0;
        private String[] arg0_type_info = new String[]{'arg0','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0'};
    }
    public class MostrarSexo {
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class actualizarUsuario {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        public String arg4;
        private String[] arg0_type_info = new String[]{'arg0','http://newpackage/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://newpackage/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://newpackage/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://newpackage/',null,'0','1','false'};
        private String[] arg4_type_info = new String[]{'arg4','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3','arg4'};
    }
    public class eliminarUsuario {
        public String arg0;
        private String[] arg0_type_info = new String[]{'arg0','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0'};
    }
    public class insertarUsuarioResponse {
        public Boolean return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class MostrarCedula {
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class MostrarApellido {
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class MostrarDireccion {
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class helloResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class MostrarSexoResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class insertarUsuario {
        public String arg0;
        public String arg1;
        public String arg2;
        public String arg3;
        public String arg4;
        private String[] arg0_type_info = new String[]{'arg0','http://newpackage/',null,'0','1','false'};
        private String[] arg1_type_info = new String[]{'arg1','http://newpackage/',null,'0','1','false'};
        private String[] arg2_type_info = new String[]{'arg2','http://newpackage/',null,'0','1','false'};
        private String[] arg3_type_info = new String[]{'arg3','http://newpackage/',null,'0','1','false'};
        private String[] arg4_type_info = new String[]{'arg4','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'arg0','arg1','arg2','arg3','arg4'};
    }
    public class hello {
        public String name;
        private String[] name_type_info = new String[]{'name','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'name'};
    }
    public class MostrarCedulaResponse {
        public String return_x;
        private String[] return_x_type_info = new String[]{'return','http://newpackage/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://newpackage/','false','false'};
        private String[] field_order_type_info = new String[]{'return_x'};
    }
    public class proceso_wcPort {
        public String endpoint_x = 'http://localhost:8084/Ejemplo_Servicio_Web/proceso_wc';
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x;
        private String[] ns_map_type_info = new String[]{'http://newpackage/', 'newpackage'};
        public Boolean insertarUsuario(String arg0,String arg1,String arg2,String arg3,String arg4) {
            newpackage.insertarUsuario request_x = new newpackage.insertarUsuario();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            request_x.arg4 = arg4;
            newpackage.insertarUsuarioResponse response_x;
            Map<String, newpackage.insertarUsuarioResponse> response_map_x = new Map<String, newpackage.insertarUsuarioResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'insertarUsuario',
              'http://newpackage/',
              'insertarUsuarioResponse',
              'newpackage.insertarUsuarioResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public Boolean actualizarUsuario(String arg0,String arg1,String arg2,String arg3,String arg4) {
            newpackage.actualizarUsuario request_x = new newpackage.actualizarUsuario();
            request_x.arg0 = arg0;
            request_x.arg1 = arg1;
            request_x.arg2 = arg2;
            request_x.arg3 = arg3;
            request_x.arg4 = arg4;
            newpackage.actualizarUsuarioResponse response_x;
            Map<String, newpackage.actualizarUsuarioResponse> response_map_x = new Map<String, newpackage.actualizarUsuarioResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'actualizarUsuario',
              'http://newpackage/',
              'actualizarUsuarioResponse',
              'newpackage.actualizarUsuarioResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String MostrarSexo() {
            newpackage.MostrarSexo request_x = new newpackage.MostrarSexo();
            newpackage.MostrarSexoResponse response_x;
            Map<String, newpackage.MostrarSexoResponse> response_map_x = new Map<String, newpackage.MostrarSexoResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'MostrarSexo',
              'http://newpackage/',
              'MostrarSexoResponse',
              'newpackage.MostrarSexoResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String hello(String name) {
            newpackage.hello request_x = new newpackage.hello();
            request_x.name = name;
            newpackage.helloResponse response_x;
            Map<String, newpackage.helloResponse> response_map_x = new Map<String, newpackage.helloResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'hello',
              'http://newpackage/',
              'helloResponse',
              'newpackage.helloResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public Boolean buscarUsuarioCedula(String arg0) {
            newpackage.buscarUsuarioCedula request_x = new newpackage.buscarUsuarioCedula();
            request_x.arg0 = arg0;
            newpackage.buscarUsuarioCedulaResponse response_x;
            Map<String, newpackage.buscarUsuarioCedulaResponse> response_map_x = new Map<String, newpackage.buscarUsuarioCedulaResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'buscarUsuarioCedula',
              'http://newpackage/',
              'buscarUsuarioCedulaResponse',
              'newpackage.buscarUsuarioCedulaResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public Boolean eliminarUsuario(String arg0) {
            newpackage.eliminarUsuario request_x = new newpackage.eliminarUsuario();
            request_x.arg0 = arg0;
            newpackage.eliminarUsuarioResponse response_x;
            Map<String, newpackage.eliminarUsuarioResponse> response_map_x = new Map<String, newpackage.eliminarUsuarioResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'eliminarUsuario',
              'http://newpackage/',
              'eliminarUsuarioResponse',
              'newpackage.eliminarUsuarioResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String MostrarCedula() {
            newpackage.MostrarCedula request_x = new newpackage.MostrarCedula();
            newpackage.MostrarCedulaResponse response_x;
            Map<String, newpackage.MostrarCedulaResponse> response_map_x = new Map<String, newpackage.MostrarCedulaResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'MostrarCedula',
              'http://newpackage/',
              'MostrarCedulaResponse',
              'newpackage.MostrarCedulaResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String MostrarApellido() {
            newpackage.MostrarApellido request_x = new newpackage.MostrarApellido();
            newpackage.MostrarApellidoResponse response_x;
            Map<String, newpackage.MostrarApellidoResponse> response_map_x = new Map<String, newpackage.MostrarApellidoResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'MostrarApellido',
              'http://newpackage/',
              'MostrarApellidoResponse',
              'newpackage.MostrarApellidoResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String MostrarDireccion() {
            newpackage.MostrarDireccion request_x = new newpackage.MostrarDireccion();
            newpackage.MostrarDireccionResponse response_x;
            Map<String, newpackage.MostrarDireccionResponse> response_map_x = new Map<String, newpackage.MostrarDireccionResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'MostrarDireccion',
              'http://newpackage/',
              'MostrarDireccionResponse',
              'newpackage.MostrarDireccionResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
        public String MostrarNombre() {
            newpackage.MostrarNombre request_x = new newpackage.MostrarNombre();
            newpackage.MostrarNombreResponse response_x;
            Map<String, newpackage.MostrarNombreResponse> response_map_x = new Map<String, newpackage.MostrarNombreResponse>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              '',
              'http://newpackage/',
              'MostrarNombre',
              'http://newpackage/',
              'MostrarNombreResponse',
              'newpackage.MostrarNombreResponse'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.return_x;
        }
    }
}